### ISSUE TITLE
Everything works and getting this errors/warnings during hover with placeholder:

### ISSUE THREAD

**Issue by peppydip** [algoz098/vue-player#4]
Everything works as expected but getting constant error messages during hover:

```
vue.runtime.esm.js:619 [Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'buffered' of undefined"

found in

---> <VideoPlaceholder> at node_modules/@algoz098/vue-player/src/components/videoPlaceholder.vue
       <VuePlayer> at node_modules/@algoz098/vue-player/src/components/player.vue

vue.runtime.esm.js:1888 TypeError: Cannot read property 'buffered' of undefined
    at VueComponent.atProgress (videoPlaceholder.vue:71)
```

also

```
Error in v-on handler: "IndexSizeError: Failed to execute 'start' on 'TimeRanges': The index provided (0) is greater than or equal to the maximum bound (0)."

found in

---> <VideoPlaceholder> at node_modules/@algoz098/vue-player/src/components/videoPlaceholder.vue
       <VuePlayer> at node_modules/@algoz098/vue-player/src/components/player.vue

DOMException: Failed to execute 'start' on 'TimeRanges': The index provided (0) is greater than or equal to the maximum bound (0).
    at VueComponent.atProgress (http://localhost:8080/js/chunk-vendors.js:3335:19)
    at invokeWithErrorHandling (http://localhost:8080/js/chunk-vendors.js:39561:26)
    at HTMLVideoElement.invoker (http://localhost:8080/js/chunk-vendors.js:39886:14)
    at HTMLVideoElement.original._wrapper (http://localhost:8080/js/chunk-vendors.js:44609:25)
```

**Comment by algoz098** [comment]
Hi, cause of time constrain, i can't keep updating this as i want. But if you create a PR, i will review it and release.

Please feel free to do so! Thanks!

**Comment by ptsneves** [comment]
Addressed in https://github.com/algoz098/vue-player/pull/47
